version: '3.8'
services:
  db:
    image: 'mysql:8.2.0'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  webserver:
    image: 'httpd:2.4.58'
    ports:
      - '9271:80'
    volumes:
      - '../app:/var/www/html'
      - './apache/my-httpd.conf:/usr/local/apache2/conf/httpd.conf'
  php:
    image: 'php:7.4.33-fpm'
    volumes:
      - '../app:/var/www/html'