version: '3.8'
services:
  db:
    image: 'bamboo_mysql'
    build:
      context: '..'
      dockerfile: 'docker/mysql/Dockerfile'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bambooinvoice
      - MYSQL_USER=bamboo
      - MYSQL_PASSWORD=bamboo
    volumes:
      - 'db_data:/var/lib/mysql'
  webserver:
    build:
      context: '..'
      dockerfile: 'docker/apache/Dockerfile'
    volumes:
      - './ssl/:/usr/local/apache2/ssl/'
  php:
    build:
      context: '..'
      dockerfile: 'docker/php/Dockerfile'
volumes:
  db_data: ~