version: '3.8'
services:
  db:
    volumes:
      - '../app/bambooinvoice.sql:/docker-entrypoint-initdb.d/init.sql'
  webserver:
    image: 'bamboo_httpd_dev'
    build:
      target: 'dev'
    volumes:
      - '../app:/var/www/html'
      - './apache/httpd.conf:/usr/local/apache2/conf/httpd.conf'
      - './apache/sites/:/usr/local/apache2/conf/sites/'
    ports:
      - '127.0.0.1:9271:80'
      - '127.0.0.1:8443:443'
  php:
    image: 'bamboo_php_dev'
    build:
      target: 'dev'
    volumes:
      - '../app:/var/www/html'
      - './php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
      - './php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    environment:
      - CI_ENV=development
  pma:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '9999:80'