<?php  
if (!defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your Code Igniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://www.your-site.com/
|
*/
$config['base_url']	= 'http://localhost:9271';
// This should be a full address, with a slash.  For example, here's what
// I use on bambooinvoice.net:
//$config['base_url']	= 'http://localhost/bamboo';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
 *$config['uri_protocol']	= 'REQUEST_URI';
*/
//http://www.markflint.net/enable-codeigniter-for-xdebug/
$config['uri_protocol']	= 'PATH_INFO';
//$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by Code Igniter.
| For more information please see the user guide:
|
| http://www.codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://www.codeigniter.com/user_guide/general/core_classes.html
| http://www.codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
//http://www.markflint.net/enable-codeigniter-for-xdebug/
//was removed in codeigniter 3.x
//$config['permitted_uri_chars'] = '';
//$config['permitted_uri_chars'] = 'a-z 0-9~%.:_-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default Code Igniter uses search-engine friendly segment based URLs:
| www.your-site.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| www.your-site.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The two other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| www.your-site.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since Code Igniter is designed primarily to
| use segment based URLs.
|
*/
//http://www.markflint.net/enable-codeigniter-for-xdebug/
//$config['enable_query_strings'] = FALSE;
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to 
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging
| 	0 = Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/logs/ folder.  Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Sessions class with encryption
| enabled you MUST set an encryption key.  See the user guide for info.
|
*/
//old key with mcrypt
$config['encryption_key'] = 'bamboo_encryption_key_Gg2F5';
//new key with AES 128 - 16byte kez
//$config['encryption_key'] = 'MZ6d6oLZvOwMp4VE';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'session_cookie_name' = the name you want for the cookie
| 'encrypt_sess_cookie' = TRUE/FALSE (boolean).  Whether to encrypt the cookie
| 'session_expiration'  = the number of SECONDS you want the session to last.
|  by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'time_to_update'		= how many seconds between CI refreshing Session Information
|
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
*/
$config['sess_use_database']	= TRUE;
//$config['sess_driver'] 			= "files";
$config['sess_driver'] 			= "database";
//$config['sess_save_path'] = 'C:/devsoftware/EasyPHP/data/localweb/bambooinvoice/application/sessions';
$config['sess_save_path']		= "bamboo_sessions";
$config['sess_cookie_name']		= 'bamboo_sessions';
$config['sess_expiration']		= 0;
//$config['sess_encrypt_cookie']	= TRUE;

$config['sess_table_name']		= 'sessions';
$config['sess_match_ip']		= FALSE;
//$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update'] 	= 300;
//for files setting
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
|
*/
$config['cookie_prefix']	= 'bamboo';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;
/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = TRUE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_token_name_bamboo';
$config['csrf_cookie_name'] = 'csrf_cookie_name_bamboo';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = FALSE;
$config['csrf_exclude_uris'] = array('logout/confirm','invoices/delete.*+','clients/delete.*+'); 
/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Hidden Bamboo Settings
|--------------------------------------------------------------------------
|
| These are settings that Bamboo uses in its day to day operations that are
| not worth their own 'setting' per se, but that some users may want to change
| in their individual setups
|
*/
// setting 'unique_invoice_per_client' to TRUE will cause last-used invoice
// numbers to be controlled by the individual client, rather then globally
$config['unique_invoice_per_client'] = FALSE;

// Quebec Mode: In some places (notably Quebec, Canada), taxes are calculated ON the
// taxes. Sounds crazy, but its true. If the quebec_mode flag is set to TRUE, we'll
// calculate the total following this pattern. 
$config['quebec_mode'] = FALSE;

// setting 'currency_decimal' will use this character instead of a '.' to separate
// the cents.  For example: $24.67 vs $24,67 vs $24_67... or whatever
$config['currency_decimal'] = '.';

// setting 'currency_thousands' will use this character instead of a ' to separate
// the thousand.  For example: $2'400.00 or $2,400.00 or whatever
$config['currency_thousands'] = '\'';

// setting 'show_profiler' to TRUE will cause profiler information to automatically 
// load on the bottom of every page (except the installer)
$config['show_profiler'] = FALSE;

// setting 'logo_base_url' to TRUE will BambooInvoice to force the path to your logo
// with 'http://yoursite.com/' as opposed to '/site/www/bamboo/' or a similar path
$config['logo_base_url'] = FALSE;

// setting 'download_filename_prefix' will allow you to customize the filename used in
// utitlies > Download backup
$config['download_filename_prefix'] = 'bambooinvoice';

// setting 'show_client_notes' to TRUE will make any client notes written on ALL invoices print
// into the PDF versions of those invoices also. This includes invoices that were first
// printed without those notes visible; on a reprint they will be included.
$config['show_client_notes'] = FALSE;

// this controls how many characters (approximately) of the first item on the invoice appear
// in the invoices summary table. Set it to 0 if you do not want this to appear at all.
$config['short_description_characters'] = 50;

// this controls how dates display throughout BambooInvoice
// 'day_month_year' gives 1 January 2009
// 'day_month_year_dots' gives 1.06.2009
// 'default' gives January 1, 2009
$config['invoice_date_format'] = 'default';

// this automates the sending of all your emails to a set recipient via blind copy.
// EXAMPLE $config['additional_email_copies'] = array('user@example.com');
// EXAMPLE $config['additional_email_copies'] = array('user1@example.com', 'user2@example.com');


/*
|--------------------------------------------------------------------------
| Autoload Custom Controllers
|--------------------------------------------------------------------------
|
*/
// The PHP file extension
// this global constant is deprecated.
define('EXT', '.php');

if(!function_exists('myAutoload')){
    function myAutoload($class) {
        if (substr($class,0,3) !== 'CI_') {
            if (file_exists($file = APPPATH . 'core/' . $class . EXT)) {
                include $file;
            }
        }
    }
}

spl_autoload_register('myAutoload');



/* End of file config.php */
/* Location: ./system/application/config/config.php */